name: Build and deploy ASP.Net Core app to Azure Web App - WhereToBinge

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run Tests
        run: dotnet test --configuration Release --no-restore --verbosity normal

      - name: Install Roslynator CLI
        run: dotnet tool install --global dotnet-roslynator --version 3.5.0 --source https://api.nuget.org/v3/index.json


      - name: Static Code Analysis
        run: |
          dotnet tool install --global dotnet-roslynator --version 3.5.0
          dotnet roslynator analyze --solution-path WhereToBingeFinal.sln --severity-minor --severity-moderate --severity-warning

      - name: Publish to Azure Web App
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'WhereToBinge'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3D16BA7FC0A14F6F86B596653AC3F6B2 }}
          package: .
